# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4303059d9f23e3f087a35780368c3e038a023afeadcc0f9c9e25475c5a9e9de0960a3e76fb4d80b412133891db0df4352cc52a042c512055d6350168e5a8ed1

test:
  secret_key_base: 1e01b61f575850a20d8c081915f1247d3e41d3123d079e4f2cab506d701ac4e19ec9c7ce033f4615eec44d48af6f82d9f7e7ef20a34342cbab66f454ffd9fd10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
